services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/.venv
    command: uv run uvicorn app.backend.main:app --host 0.0.0.0 --port 8000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
